# Generated by Django 3.1 on 2020-12-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availablejobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employeemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email_id', models.EmailField(max_length=30)),
                ('phone_num', models.IntegerField()),
                ('employee_gender', models.CharField(choices=[('M', 'Male'), ('F', 'FeMale')], max_length=1)),
                ('employee_address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('employee_jobs', models.ManyToManyField(blank=True, to='app12.Availablejobs')),
            ],
        ),
    ]
